### PR TITLE
[addon] show application Version as ETS

### PR DESCRIPTION
**Pull request by olterion**
The ETS shows the version of the application as hex number with a minor version after a point. This behavior is recreated with this change.

Now it looks like:

app_version

### CODE REVIEW

**Comment by thewhobox** [comment]
Im not shure if this is a good option.
The "Replaces the following Versions" is decimal (17 not 1.1).
You should at least show the decimal verstion too, or allow both (dec and ets, there is enough room for another textbox :))

Also it doesnt work on my project:
image

**Comment by thewhobox** [comment]
If i enter 1 and 5 it makes 1.5?

**Comment by olterion** [comment]
Here I made changes to add a new field below the original version in application tab.
So the user can choose, if he wants to change the version like ETS style or XML style.

Yes, if you enter 1 and 5 it will be version 1.5
If you want to change the mayor version, you can set the cursor to the place and change it.

**Comment by thewhobox** [comment]
Perfect, could you fix it so Versions lower 16 are not shown as hex :)
Then i will merge it.

**Comment by olterion** [comment]
Now every not numeric version is not shown in the ETS version field.
It will be blank, if the version contains a not numeric digit (as hex conversion)

**Comment by thewhobox** [comment]
There are still versions that dont work.

10 - 15
25 - 31
etc...
so every version which would be x.10-15 since ToString("X") would do x.A-F

why not something like:
```C#
int major = Math.Floor(value / 16);
int minor = value % 16;
return $"{major}.{minor}"
```

**Comment by olterion** [comment]
I added some code to convert the input back to int.
Now there should be no possibility to enter a wrong version number into the textfield.

**Comment by thewhobox** [comment]
this works perfect :)

**Pull request merged**
